### ISSUE TITLE
Website baru untuk PERKODI

### ISSUE THREAD

**Issue by firewalker06** [perkodi-org/perkodi#1]
Kami ingin membuka peluang untuk merekrut kontributor untuk membangun website PERKODI. Website PERKODI akan berupa halaman statis, disarankan untuk menggunakan [nanoc](https://nanoc.ws/).

Kontributor akan diundang masuk ke dalam organisasi Github https://github.com/perkodi-org. Mengenai konten, akan dibahas setelah kontributor sudah dipilih.

Silakan tinggalkan komentar "Saya tertarik untuk berkontribusi" di issue ini, kemudian join Slack group id-ruby http://ruby.id/slack dan masuk ke channel `#perkodi`.

**Comment by ukazap** [comment]
Saya tertarik untuk berkontribusi

**Comment by mirzalazuardi** [comment]
mau juga dong ikut bantu develop mas @firewalker06

**Comment by ghost** [comment]
Saya tertarik untuk berkontribusi

**Comment by firewalker06** [comment]
Terima kasih @ukazap @mirzalazuardi @mappuj1, kita diskusi lanjut di Slack yah.

**Comment by edwardfernando** [comment]
Saya tertarik untuk berkontribusi @firewalker06

**Comment by donnykurnia** [comment]
Saya tertarik untuk berkontribusi
